Coding support
blase147/Mobile-first-Portfolio-Project pull request #1
Opened 2022-08-19 21:52 UTC by blase147

This is the Mobile-first Portfolio Project

2022-08-20 20:56 UTC, prolajumokeoni reviewed
Hi @blase147, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has webhint errors please fix this 👍🏿 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-08-20 22:36 UTC, MeqdamAlqudah reviewed
Hi @blase147  , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has linter errors.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-08-20 22:41 UTC, prolajumokeoni commented
Hi @blase147 kindly fix the stylelint linter errors

2022-08-20 22:43 UTC, prolajumokeoni reviewed
Hi @blase147  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project,  that has linter errors.
Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-08-20 23:47 UTC, ElsonOtake requested changes
STATUS: CHANGES REQUIRED 🟡 

Hi @blase147,

Good job so far! 🎉 🎉 
There are some issues that you still need to work on to go to the next project but you are almost there! 🥲 🥲 

![woohoo-youre-almost](https://user-images.githubusercontent.com/77038610/154921145-1f7bb8f6-c843-4ba5-a534-6b840c600558.jpeg)

## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️

## Required Changes ♻️
_Check the comments under the review._

- [ ] Please create a descriptive Pull Request as requested for your project. More details in [Document your repo in a professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/clean_repo.md).
- [ ] Please make sure that your design follow the Figma template. Was not possible to check the design because of the use of `position absolute` on your styling.


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-20 23:47 UTC, ElsonOtake commented on index.html
> +        <h3>I’am a Software Developer</h3>
- [ ] Please use the correct tag for this text, in this case, is a `<p>` tag. This way will be semantically correct and the screen readers and other technologies will thank you.

2022-08-20 23:47 UTC, ElsonOtake commented on index.html
> +        </div>
- [ ] Please use `<ul>` for the list of icons and `<li>` for each icon. It's semantically correct and will improve the readability of your code.
- [ ] Please add the image files to the `img` folder. Just one of the images is there.

2022-08-20 23:47 UTC, ElsonOtake commented on index.html
> +    <div class="my-recent-works">
- [ ] Please use `<section>` instead of `<div>` for semantic reasons, as required for this project.
- [ ] Kindly create the background image for this section as provided on the Figma template. Use CSS background image. It's a requirement for this project also.

2022-08-20 23:47 UTC, ElsonOtake commented on index.html
> +        </div>
- [ ] Please use `<ul>` for the list of technologies and `<li>` for each technology. It's semantically correct and will improve the readability of your code.

2022-08-20 23:47 UTC, ElsonOtake commented on index.html
> +      </div>
- [ ] Please use `<ul>` for the list of technologies and `<li>` for each technology. It's semantically correct and will improve the readability of your code.

2022-08-20 23:47 UTC, ElsonOtake commented on index.html
> +          <div class="tag">Ruby</div>
- [ ] Please use `<ul>` for the list of technologies and `<li>` for each technology. It's semantically correct and will improve the readability of your code.

2022-08-20 23:47 UTC, ElsonOtake commented on index.html
> +        <button type="button">See Project</button>
- [ ] Please use the required styling for the button. Including styling: Active, Hover, and Pressed (see design). It's a requirement of this project.

2022-08-20 23:47 UTC, ElsonOtake commented on index.html
> +      <button class="see-projects">See Project</button>
- [ ] Please use the required styling for the button. Including styling: Active, Hover, and Pressed (see design). It's a requirement of this project.

2022-08-20 23:47 UTC, ElsonOtake commented on index.html
> +          <button type="button">Get Resume</button>
- [ ] Please use the required styling for the button. Including styling: Active, Hover, and Pressed (see design). It's a requirement of this project.

2022-08-20 23:47 UTC, ElsonOtake commented on index.html
> +        <img src="img/illustration-header-mobile.png" alt="">
- [ ] Please use this image as CSS Background image. For more information check this [link](https://www.w3schools.com/cssref/pr_background-image.asp).

2022-08-20 23:47 UTC, ElsonOtake commented on style.css
> +  position: absolute;
- [ ] Please avoid the use of `position absolute` in this case. Remove this declaration from your code. Your code is looking like this: 
<img width="822" alt="Screen Shot 2022-08-20 at 8 34 38 PM" src="https://user-images.githubusercontent.com/47673311/185769437-bcd12197-94cd-4c56-9cea-0ec540e82ae6.png">
Check for other cases in your code.

2022-08-20 23:47 UTC, ElsonOtake commented on style.css
> +  position: absolute;
- [ ] Please avoid the use of `position absolute` as required before.

2022-08-20 23:47 UTC, ElsonOtake commented on style.css
> +  position: absolute;
- [ ] Please avoid the use of `position absolute` as required before.

2022-08-20 23:47 UTC, ElsonOtake commented on style.css
> +  position: absolute;
- [ ] Please avoid the use of `position absolute` as required before.

2022-08-20 23:47 UTC, ElsonOtake commented on README.md
> -
- [ ] Please create a more descriptive README file for your project - please use all fields of [this template](https://github.com/microverseinc/readme-template) but remember to customize it to your project.

2022-08-20 23:47 UTC, ElsonOtake commented on menu-mobile.html
> +</html>
- [ ] Please remove unused files from your project. Decreases readability and makes your code more polluted.

2022-08-20 23:47 UTC, ElsonOtake commented on multi-post-stories.html
> +</html>
- [ ] Please remove unused files from your project. Decreases readability and makes your code more polluted.

2022-08-22 08:25 UTC, prolajumokeoni commented
Hi @blase147 kindly fix linter errors and please fix broken links to images, currently this is what your page looks like 👍🏿 
![Screenshot_398](https://user-images.githubusercontent.com/69638013/185875144-27433321-bbe4-49d1-9012-8255e5a701e8.png)

2022-08-22 09:39 UTC, prolajumokeoni requested changes
Hi @blase147, 
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ No linter errors
✔️ Git flow was correctly used 
✔️  Good PR title and Description



## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-22 09:39 UTC, prolajumokeoni commented on index.html
> +  </div>
- [ ] Kindly make the headline section wrapper a section tag instead of div, this will make your website more semantic 👍🏿 

- [ ] Kindly add the background image as a background image in css and not using an img tag, currently this is missing in your design 👍🏿 

Figma Design          |  Your design     
:-------------------------:|:-------------------------:
![Template 2-Main-Mobile](https://user-images.githubusercontent.com/69638013/185887916-fefa8d1f-e6be-4e6e-ac65-e49914ffb85b.png) |  ![Screenshot_399](https://user-images.githubusercontent.com/69638013/185887830-47b11162-05c6-48d3-a890-232a9ff7d16b.png)

2022-08-22 09:39 UTC, prolajumokeoni commented on index.html
> +      <li><img src="img/Icon-Medium.png" alt="icon"></li>
- [ ] Kindly make each image  icon in an `a` tag,  currently, your image icons  appear broken please fix this 👍🏿

2022-08-22 09:39 UTC, prolajumokeoni commented on index.html
> +    <p>I’am a Software Developer</p>
- [ ] Kindly make sure the subtitle header uses a hx tag between h2 - h6, this will be more semantic 😉

2022-08-22 09:39 UTC, prolajumokeoni commented on style.css
> +  width: 375px;
- [ ] Kindly avoid using static widths in your project, because for mobile screen sizes larger than 375 the design will not take the entire width 👍🏿

2022-08-22 09:39 UTC, prolajumokeoni commented on style.css
> +  width: 375px;
- [ ] Kindly avoid using static widths in your project, because for mobile screen sizes larger than 375 the design will not take the entire width 👍🏿

2022-08-22 11:49 UTC, sja-thedude requested changes
## Invalid Code Review Request ❌

Hi @blase147, This is @sja-thedude your code reviewer.

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

You have submitted a project in the dashboard, that is for portfolio finish but your project in the repo is about portfolio setup. Make sure to submit correctly.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-08-22 11:51 UTC, blase147 commented on style.css
> +  width: 375px;
Ok, I used vw and em but my layout got larger and disorganized. What do I do?

2022-08-22 13:17 UTC, blase147 commented on style.css
> +  width: 375px;
I am currently unable to for errors on GitHub. Please what can I do now?

2022-08-22 13:38 UTC, blase147 commented
@sja-thedude. I am currently unable to check for errors on Github. Any ideas?

2022-08-22 15:17 UTC, Munsa1 approved these changes
Hi @blase147, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
:heavy_check_mark: Descriptive Readme
:heavy_check_mark: Passing Linters
:heavy_check_mark: Correct Gitflow

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-23 00:19 UTC, Omar-Muhamad reviewed
# Invalid ❌

Hi @blase147,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

Your Code Review Request is marked as invalid for these reasons:

- [ ] You didn't document your work professionally:
   - Your Pull Request doesn't have a meaningful title describing what you did inside it.
   - Your Pull Request doesn't have a descriptive summary with every change you did.
- [ ] Please make a new Pull Request for every milestone of your project and kindly don't submit different milestones with the same Pull Request.
- [ ] Please give the branch you compare to the master(main) branch a meaningful name like `mobile version` for this milestone.


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

2022-08-23 09:54 UTC, merged