Adding javascript dynamics to portfolio project
blase147/Mobile-first-Portfolio-Project pull request #12
Opened 2022-09-12 16:40 UTC by blase147

We created an external javascript file and added some javascript dynamics to the portfolio project.

2022-09-12 17:09 UTC, leonardodiasb commented on js/index.js
> +});
- [ ] If a user accidentally clicks on the blank space below the menu options, it closes the mobile menu. This is not the expected behavior, the mobile menu should be closed when the user clicks on the 'X' button or when the user clicks on the menu options. Please fix this functionality(remember that when the user clicks on the menu options the menu should close).
 -
<img width="704" alt="image" src="https://user-images.githubusercontent.com/61919617/189714691-4cc657b3-50db-43c4-b9f5-a012620d2f14.png">

2022-09-12 17:17 UTC, leonardodiasb commented on index.html
> +        <a class="intern-link" href="#contact">Contact</a>
- [ ] I see that you applied some classes that are not being used in your CSS file like the 'inter-link', 'intern-link', and also the id 'nav-items'. Kindly remove unused classes or ids to clean your HTML file.

2022-09-12 17:20 UTC, leonardodiasb commented on index.html
> +    <!-- <p id="demo" ></p> -->
- [ ] Please remove commented out code to clean your HTML or CSS file. Please check [best practices for HTML & CSS](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md).

2022-09-12 17:20 UTC, leonardodiasb commented on style/style.css
> +  /* display: none; */
- [ ] Please remove commented out code to clean your HTML or CSS file. Please check [best practices for HTML & CSS](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md).

2022-09-12 17:20 UTC, leonardodiasb commented on style/style.css
> +  /* justify-content: center; */
- [ ] Please remove commented out code to clean your HTML or CSS file. Please check [best practices for HTML & CSS](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md).

2022-09-12 17:20 UTC, leonardodiasb commented on style/style.css
> +  /* align-items: center; */
- [ ] Please remove commented out code to clean your HTML or CSS file. Please check [best practices for HTML & CSS](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md).

2022-09-12 17:20 UTC, leonardodiasb commented on style/style.css
> +  /* background-attachment: relative; */
- [ ] Please remove commented out code to clean your HTML or CSS file. Please check [best practices for HTML & CSS](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md).

2022-09-12 17:21 UTC, leonardodiasb commented on style/style.css
> +    /* background-attachment: relative; */
- [ ] Please remove commented out code to clean your HTML or CSS file. Please check [best practices for HTML & CSS](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md).

2022-09-12 17:21 UTC, leonardodiasb commented on style/style.css
> +    /* align-content: cent; */
- [ ] Please remove commented out code to clean your HTML or CSS file. Please check [best practices for HTML & CSS](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md).

2022-09-12 17:21 UTC, leonardodiasb commented on style/style.css
> +    /* background-attachment: relative; */
- [ ] Please remove commented out code to clean your HTML or CSS file. Please check [best practices for HTML & CSS](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md).

2022-09-12 17:23 UTC, leonardodiasb commented on style/style.css
> +  /* font-family: 'Inter'; */
- [ ] I see that you used the font family that was provided by the template but commented on this code. Please, import this font so you can use it in your portfolio and it can look more similar to the provided template.

2022-09-13 06:33 UTC, HAMMAS-SALEEM requested changes
# Required Changes :recycle:
![almost-there](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Hey @zied2112, @blase147 :wave:

## Highlights :1st_place_medal:

:heavy_check_mark: Following GitFlow
:heavy_check_mark: Descriptive PR Title
:heavy_check_mark: Descriptive PR Summary

Good job on implementing some of the changes requested by the previous reviewer, there are some issues that you still need to work on to go to the next project but you are almost there! :blush:

# Optional

_See Below Comments_

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-13 06:33 UTC, HAMMAS-SALEEM commented on index.html
> +      <img id="menu-button" class="menu" src="img/menu.png" alt="menu">
- [ ] As the previous reviewer suggested, please wrap this image with a `button` tag because this is a clickable item 🤔

2022-09-13 06:33 UTC, HAMMAS-SALEEM commented on index.html
>        </div>
- [ ] As the previous reviewer suggested, please wrap this icon with a `button` tag instead of `div` tag because this is a clickable item 🤔

2022-09-13 06:33 UTC, HAMMAS-SALEEM commented on js/index.js
> +// });
- [ ] Please remove the commented code to make your code clean as requested by the previous reviewer 👍

2022-09-13 06:33 UTC, HAMMAS-SALEEM commented on index.html
> +        <div class="line-separation"></div>
- [ ] Whenever you click on any of the links, it should make the menu hidden as requested by the previous reviewer but in your mobile design when you click on any of the links it doesn't hide the mobile menu. Kindly, fix this issue :blush:

2022-09-13 07:43 UTC, blase147 commented on js/index.js
> +});
Sorry, do you mean we should make the mobile menu sticky?

2022-09-13 09:00 UTC, m05e5 approved these changes
# Status: ✔️ Project Approved ✔️ 

Hello @blase147 and @zied2112  🔥 

Good job on implementing the requested changes. Well Done.
Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

![goodjob](https://user-images.githubusercontent.com/60631456/130260474-3c2d5e5c-96df-43de-a0db-8d0059c10862.gif)


Now you can merge this branch 🚀 

Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

- [ ] [optional] To improve UX, I'll recommend using a `position:fixed;` on your mobile menu. This is to prevent the user from seeing the rest of the page when the mobile menu is opened 
<img width="376" alt="image" src="https://user-images.githubusercontent.com/37901469/189859111-c7cef6ea-1af9-4319-a9ea-e0a43bbf7803.png">
 

_m05e5_

### 💻 👩🏽‍💻  Happy Coding!  👨🏽‍💻 🖥️

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-13 09:12 UTC, merged