Responsive-Portfolio-Project
blase147/Mobile-first-Portfolio-Project pull request #7
Opened 2022-09-02 10:37 UTC by blase147

This is an updated version of my Portfolio project with both mobile and desktop responsiveness and scalability

2022-09-02 12:19 UTC, cynthiainga requested changes
Hi @blase147, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Highlights

- [ ] No linters errors ✔️ 
- [ ] Good commit messages ✔️ 
- [ ] Used correct Github flow ✔️ 

## Required Changes ♻️

- [ ] Please kindly check the comments under the review 👇 👇
- [ ] Also after finish all the required changes please kindly verify if the styling of your mobile version is okay 👌 ✅ 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-02 12:19 UTC, cynthiainga commented on index.html
>    <section class="about">
- [ ] Please make sure your `about` section design sticks as much as possible to the [figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1%3A1471), e.g., font, colors, images, text, margins,... 🙃

> |     |  Your design : screen size => 1440px                     |  Figma design                   |     |
> | --- | ----------------------------------- | ------------------------------------ | --- |
> |     |<img width="719" alt="Screen Shot 2022-09-02 at 13 56 41" src="https://user-images.githubusercontent.com/74501523/188138272-42aaed5d-6f20-408d-b754-2e8a82df7f56.png">| <img width="684" alt="Screen Shot 2022-09-02 at 13 57 02" src="https://user-images.githubusercontent.com/74501523/188138310-9fc335bb-ed10-4b38-9fe8-8702d20bc1bc.png">|

2022-09-02 12:19 UTC, cynthiainga commented on index.html
>    <footer>
- [ ] Please make sure your `footer` section design sticks as much as possible to the [figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1%3A1471), e.g., font, colors, images, text, margins,... 🙃

> |     |  Your design : screen size => 1440px                     |  Figma design                   |     |
> | --- | ----------------------------------- | ------------------------------------ | --- |
> |     |<img width="721" alt="Screen Shot 2022-09-02 at 14 01 29" src="https://user-images.githubusercontent.com/74501523/188139041-949d3e62-07c3-4a95-9973-14895a9ea4b2.png">| <img width="687" alt="Screen Shot 2022-09-02 at 14 01 47" src="https://user-images.githubusercontent.com/74501523/188139072-770d7662-519f-4ca9-93ec-9adf4549ab42.png">  |

2022-09-02 12:19 UTC, cynthiainga commented on style.css
>    }
- [ ] Please kindly add all your styling for desktop in just only one media query to avoid repetition, and to have clear and clean code, you can many media queries if you need to implement different screen sizes, for example, you can have media of `min-width: 768px, min-width: 1024px, max-width: 1240px,...` but in your case, you have only one media of `min-width: 768px`.
Take a look at how you can write your code:

```css
@media only screen and (min-width: 786px) {
/*
.
 
All your styling here for screen of `min-width: 768px`
.
*/
}
```

2022-09-03 02:54 UTC, mahbubul14 requested changes
Hi @blase147 ,

Great work on making the changes requested by the previous reviewer 👏

You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

# Required Changes ♻️

- [ ] Kindly check the inline comments under the review. :arrow_down: 

###  To Highlights
:heavy_check_mark: No linter error.
:heavy_check_mark: Proper Github flow used.
:heavy_check_mark: Descriptive PR title & description.

### Optional suggestions

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.

- [ ] In your `README` file, there is no content for the "Getting Started" section. Kindly add content for the getting started section. This should be an example of how you may give instructions on setting up your project locally.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also reach me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-09-03 02:54 UTC, mahbubul14 commented on index.html
> +        </ul>
- [ ] Twitter icon is not showing on your page. Kindly fix the issue. :+1: 

> To fix the issue, image source should be `img src="img/Icon - Twitter.png"`

2022-09-03 02:54 UTC, mahbubul14 commented on index.html
> +          <h1>My Recent Works</h1>
`line 45-150`

- [ ] My Recent Works should be in one line. :+1: 

- [ ] The image for the multipost stories should move to the left side a little bit to match the Figma design. :+1: 

- [ ] Changing code after the first review, the section of your recent work is not working properly. Please make sure your work section design stick as much as possible to the [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1%3A1471), e.g., font, colors, images, text, margins,... Kindly fix the issue. :+1: 

Your design
:-------------------------:
![work2](https://user-images.githubusercontent.com/70483835/188252668-760d1ed3-0856-44d9-9f8b-95f1540005f8.png)

Figma Design
:-------------------------:
![work-figma1](https://user-images.githubusercontent.com/70483835/188252676-bbdd9be2-cb1f-4cd5-8fb0-1ddb4803a815.png)

2022-09-03 02:54 UTC, mahbubul14 commented on index.html
> +          <h1>About me</h1>
`line 152-205`

- [ ] As the previous reviewer asked, kindly make sure your work section design stick as much as possible to the Figma design, e.g., font, colors, images, text, margins,... :+1: 
Your design
:-------------------------:
![about1](https://user-images.githubusercontent.com/70483835/188253049-e8406d9a-3698-4691-814e-cf4703df1716.png)

Figma Design
:-------------------------:
![about2](https://user-images.githubusercontent.com/70483835/188253050-d0f1def2-9e94-4068-8785-e2c76d9c3452.png)

2022-09-03 04:29 UTC, blase147 commented on index.html
>    <section class="my-works">
Thanks for the review. However, I'm having a tough time knowing exactly how to fix this. When I expand my screen it lays out well as well as on mobile view, but in between is where lies the problem. I don't know what to do.

2022-09-03 04:32 UTC, blase147 commented on index.html
> +          <h1>My Recent Works</h1>
Thanks for the review. However, I'm having a tough time knowing exactly how to fix this. When I expand my screen it lays out well as well as on mobile view, but in between is where lies the problem. I don't know what to do.

2022-09-04 05:58 UTC, emmiiorji approved these changes
Hi @blase147, 

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Good Highlights ✔

- Linter checks are passing
- Adherence to GitHub flow
- Good commit messages


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-04 07:09 UTC, merged